### PR TITLE
migrate board of directors minutes

### PR DESCRIPTION
**Pull request by iisa**
from original location https://drive.google.com/drive/folders/0BzPWVMj9wWa6MVhCTGo5b1hwLVk?resourcekey=0-GpK-TEnnXU_A3W_7LCk_gA&usp=sharing

### CODE REVIEW

**Comment by mxie** [comment]
@iisa There seems to be a couple of empty files. Do you know what happened to those?

- docs/corporate-docs/board-of-directors-minutes/2018-08-18-action
- docs/corporate-docs/board-of-directors-minutes/2019-12-15-minutes

**Comment by iisa** [comment]
thanks for the second pair of eyes, @mxie , will look into it.

**Comment by ultrasaurus** [comment]
Also note, we had another board meeting, so it needs to be added:  https://docs.google.com/document/d/1XV0MxI9T-fyF8wsvRsklpvYSawGNoJ6af7mAlTfhE7Y/edit

**Comment by ultrasaurus** [comment]
files should also have `.md` suffix so that we can preview them more easily in Github

**Comment by mxie** [comment]
@ultrasaurus Is this ready to merge as is or is there more work to do?

**Comment by ultrasaurus** [comment]
see: https://github.com/bridgefoundry/operations/pull/115

**Pull request closed without merging**
